sudo: false

language: python

services:
  - docker

python:
  - "2.7"

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

# command to install dependencies
install:
  - pip install dxlclient dxlbootstrap
  - pip install .

before_script:
  - python -m dxlclient provisionconfig dxlclient/test 127.0.0.1 client -u admin -p password
  - cp dxlclient/test/dxlclient.config dxlclient/test/client_config.cfg
  - sed -i -e "s/external/unique_broker_id_1/g" -e "/local/d" dxlclient/test/client_config.cfg
  - cat dxlclient/test/client_config.cfg

# command to run tests
script:
- python setup.py install
- python tests/test_virustotal_all_examples.py
env:
  global:
    secure: 03vm4QCTPHlS5CVdLYCgIcfrm7ieLfC6Sv604NOf7vDK8a8xtGMRlR5XRMMtavWWKklwt5Ta6u1z/4AidbLFGLTRc7ySKflHlv9yrdHV6/E4+Jzf42mvaeMBjScH7OY7nlsMdyayfbhuDZmAxF0Pgkk/TZG0oPl0F6nIbP0UFA6H4Fuuu5yTJKsUey29P/hCb7fUXb2s01gvTh65s1VoJU3TFb1y/IoEwRLqRm5dEcec20+VufmV217oBzOSUrRuHwxT0FkX/Eg8p4QPLRIiv1nZ2XQkeYmUk6H5yIONL6pv6g8syFhzHav8OMJ1wweTYNzWtqDD+MQzuAian44VQ7zsVqqpzPgG1Y7ZS15DUpNlIv1eR5oKgyG6dXpWSJFbb/zOCXsNvDdXKlrbxTh/k2PQ2GE0bIYOYZVh4oElPeaGVJvE6fd02LoMUPjPZQ2rGauOdYAljdIWKCAUZjtxczXthpGkl5EiFaOt6RF8UVnyRDM1KIVzjly/a0fbNml6eOuiZL/kXCREi2PkdECMZ/Ux7ru/6K2818YI2sP4TStoPebcCt+ljK3qaRD97RxgUsBWbNQLa8W2MEB9yEEAk10XxZtfIigKzifNYBy/g/DEQiE+T3dEMUOBriDrpLWt/BGEzp1KkQr8RDm81hlETSwh7RmVxLbPlxG8LflEaME=
